languageCode = "zh-CN"
languageName = "ç®€ä½“ä¸­æ–‡"
languageDirection = "ltr"
weight = 1

title = "Yefimm"
copyright = """&copy; æœ¬æ–‡æ‰€æœ‰æ–‡ç« é™¤ç‰¹åˆ«å£°æ˜å¤–ï¼Œå‡é‡‡ç”¨ [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) è®¸å¯åè®®ã€‚è½¬è½½è¯·æ³¨æ˜å‡ºå¤„ ğŸ’œ"""

[params]
  dateFormat = "2006å¹´1æœˆ2æ—¥"

  mainSections = ["posts"]
  description = "ä¸€äº›ä¸ªäººç¬”è®°"

[params.author]
  name = "Yefimm"
  image = "img/author.png"
  headline = "é€šè¿‡å®è·µè€Œå‘ç°çœŸç†ï¼Œåˆé€šè¿‡å®è·µè€Œè¯å®çœŸç†å’Œå‘å±•çœŸç†ã€‚"
  bio = "é€šè¿‡å®è·µè€Œå‘ç°çœŸç†ï¼Œåˆé€šè¿‡å®è·µè€Œè¯å®çœŸç†å’Œå‘å±•çœŸç†ã€‚"
  links = [
    #{ x-twitter = "https://twitter.com/" },
    #{ facebook = "https://facebook.com/" },
    #{ linkedin = "https://linkedin.com/" },
    #{ youtube = "https://youtube.com/" },
	{ zhihu = "https://www.zhihu.com/people/Yephgeni.Jia"},
	{ github = "https://github.com/Yefimm" }
  ]
